version: '3'

services:
  backend:
    build:
      context: ./backend
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/lost?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=88888888
      - SPRING_PROFILES_ACTIVE=prod
      - FILE_UPLOAD_DIR=/app/uploads
      - FILE_BASE_URL=http://localhost:8080/api
    volumes:
      - backend-logs:/app/logs
      - backend-uploads:/app/uploads
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    ports:
      - '3333:3333'
    depends_on:
      - backend
    volumes:
      - nginx-pid:/var/run
      - nginx-cache:/var/cache/nginx
    user: root

  db:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=88888888
      - MYSQL_DATABASE=lost
    volumes:
      - mysql-data:/var/lib/mysql
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  mysql-data:
  backend-logs:
  backend-uploads:
  nginx-pid:
  nginx-cache:
