version: 1.0

# 阿里云云效流水线配置
name: spring-boot-deploy

# 定义环境变量
variables:
  APP_NAME: lostandfound-backend
  DEPLOY_PATH: /home/admin/app
  SERVER_PORT: 8080

# 流水线阶段
stages:
  - name: build
    displayName: 构建阶段
    strategy: naturally
    steps:
      - name: maven-build
        displayName: Maven构建
        type: MAVEN
        inputs:
          workingDir: backend
          commands:
            - mvn clean package -DskipTests

  - name: deploy
    displayName: 部署阶段
    strategy: naturally
    steps:
      - name: upload-jar
        displayName: 上传JAR包
        type: UPLOAD
        inputs:
          source: backend/target/*.jar
          destination: ${DEPLOY_PATH}/app.jar
          targetServers:
            - ${TARGET_SERVER_ID}  # 在云效平台配置的目标服务器ID
            
      - name: run-deploy-script
        displayName: 执行部署脚本
        type: REMOTE_COMMAND
        inputs:
          script: |
            cd ${DEPLOY_PATH} && 
            chmod +x deploy.sh && 
            ./deploy.sh
          targetServers:
            - ${TARGET_SERVER_ID}

# 触发器配置
triggers:
  push:
    branches:
      include:
        - main
        - master
    paths:
      include:
        - backend/** 