server:
  port: 8080
  servlet:
    context-path: /api
  address: 0.0.0.0

file:
  upload:
    dir: uploads
    allowed-extensions: jpg,jpeg,png,gif,webp
    max-file-size: 5
    max-request-size: 10MB
    # 基础URL配置，如果设置，文件URL将使用此URL加文件路径
    # 在生产环境中要设置为API的实际访问地址
    base-url: ${FILE_BASE_URL:http://121.40.52.9/api}

spring:
  datasource:
    url: jdbc:mysql://39.101.76.177:3306/lost_and_found?useSSL=false&serverTimezone=UTC
    username: root
    password: shuhao201028
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

  redis:
    host: localhost
    port: 6379
    password:
    database: 0
    timeout: 10000
  main:
    allow-circular-references: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.community.lostandfound.entity
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret: LostAndFoundSecretKey123!@#$%^&*()_+AABBCCDDEEFFGGHHIIJJKKLLaabbccddeeffgghhiijjkk
  expiration: 86400000 # 24 hours in milliseconds
  header: Authorization
  token-prefix: Bearer

logging:
  level:
    com.community.lostandfound: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.mybatis: INFO
  file:
    name: ./logs/lost_and_found.log
