server:
  port: 8080
  servlet:
    context-path: /api
  address: 0.0.0.0

# 通用文件上传配置
file:
  upload:
    dir: uploads
    allowed-extensions: jpg,jpeg,png,gif,webp
    max-file-size: 5
    max-request-size: 10MB

# 环境配置
spring:
  # 默认使用开发环境配置，可通过环境变量或命令行参数覆盖
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  
  # 文件上传配置
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  
  # 允许循环依赖（如有必要）
  main:
    allow-circular-references: true

# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.community.lostandfound.entity
  configuration:
    map-underscore-to-camel-case: true

# JWT配置
jwt:
  secret: LostAndFoundSecretKey123!@#$%^&*()_+AABBCCDDEEFFGGHHIIJJKKLLaabbccddeeffgghhiijjkk
  expiration: 86400000 # 24 hours in milliseconds
  header: Authorization
  token-prefix: Bearer

# 通用日志配置
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
