server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lost_and_found?useSSL=false&serverTimezone=UTC
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  redis:
    host: localhost
    port: 6379
    password: 
    database: 0
    timeout: 10000

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.community.lostandfound.entity
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret: yourSecretKey
  expiration: 86400000  # 24 hours in milliseconds
  header: Authorization
  token-prefix: Bearer

logging:
  level:
    com.community.lostandfound: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.mybatis: INFO 