# 本地开发环境配置
server:
  port: 8080
  servlet:
    context-path: /api
  address: 0.0.0.0

# 开发环境的文件上传配置
file:
  upload:
    dir: uploads
    allowed-extensions: jpg,jpeg,png,gif,webp
    max-file-size: 5
    max-request-size: 10MB
    # 开发环境不设置base-url，系统将自动基于当前请求生成URL
    base-url:

# 开发环境的数据库配置
spring:
  datasource:
    url: jdbc:mysql://115.29.176.56:3306/lost_and_found?useSSL=false&serverTimezone=UTC
    username: root
    password: 88888888
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # Redis配置
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
    timeout: 10000

# 开发环境日志配置 - 更详细的日志记录
logging:
  level:
    com.community.lostandfound: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.mybatis: INFO
  file:
    name: ./logs/lost_and_found.log
